##documentacion: k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-monitoring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre-monitoring-app
  template:
    metadata:
      labels:
        app: sre-monitoring-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: sre-monitoring-app
          image: sre-monitoring-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
