##SRE Monitoring Application Service
apiVersion: v1
kind: Service
metadata:
  name: sre-monitoring-appservice
spec:
  type: NodePort
  selector:
    app: sre-monitoring-app
  ports:
    - port: 8080
      targetPort: 8080

